- name: Directories are present
  file:
    path="{{ item }}"
    state=directory
    owner='{{ user }}'
    group='{{ grp }}'
    mode=0777
  with_items: directories
  tags: [jenkins]

- name: Directories are present
  file:
    path='{{ jenkins_directory }}/.ssh/'
    state=directory
    owner='{{ user }}'
    group='{{ grp }}'
    mode=0700
  tags: [jenkins]

- name: Config files are present
  copy:
    src='{{ item }}'
    dest='{{ jenkins_directory }}/.ssh/{{ item }}'
    mode=0600
    owner='{{ user }}'
    group='{{ grp }}'
  with_items: ssh
  tags: [jenkins]

- name: Config files are present
  copy:
    src='{{ item }}'
    dest='{{ jenkins_directory }}/{{ item }}'
    mode=0777
    owner='{{ user }}'
    group='{{ grp }}'
  with_items: configs
  tags: [jenkins]

- name: Plugins are present
  copy:
    src='{{ item }}'
    dest='{{ jenkins_directory }}/plugins/{{ item }}'
    mode=0777
    owner='{{ user }}'
    group='{{ grp }}'
  with_items: plugins
  tags: [jenkins]

- name: Build job directories are present
  file:
    path='{{ jenkins_directory }}/jobs/{{ item }}'
    state=directory
    mode=0777
    owner='{{ user }}'
    group='{{ grp }}'
  with_items: jobs
  tags: [jenkins]

- name: Build jobs are present
  template:
    src=build.xml.j2
    dest='{{ jenkins_directory }}/jobs/{{ item }}/config.xml'
    mode=0777
    owner='{{ user }}'
    group='{{ grp }}'
    backup=yes
  with_items: jobs
  tags: [jenkins]

- name: Container is running
  docker:
    name=jenkins
    image=jenkins:1.642.4
    ports=8080:8080
    volumes=/data/jenkins:/var/jenkins_home
  tags: [jenkins]

- name: Copy script to jenkins home
  copy:
    src='{{ item }}'
    dest=/home/jenkins/{{ item }}
    mode=0777
    owner=jenkins
    group=jenkins
    backup=yes
  with_items: home
  tags: [jenkins]
