jenkins_directory: /data/jenkins

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'
  - '{{ jenkins_directory }}/.ssh'

configs:
  - config.xml

plugins:
  - github.hpi
  - git.hpi
  - credentials.jpi
  - scm-api.hpi
  - matrix-project.jpi
  - git-client.hpi
  - github-api.hpi

jobs:
  - books-service

ssh:
  - id_rsa
  - id_rsa.pub
  - authorized_keys

home:
  - deploygoapp.sh
