- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  when: "ansible_os_family == 'Debian'"
  tags: [docker]

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: "ansible_os_family == 'RedHat'"
  tags: [docker]

- name: Docker is present Debian
  apt:
    name: docker-engine
    state: latest
  when: "ansible_os_family == 'Debian'"
  tags: [docker]


- name: Docker is present RedHat
  yum:
    name: docker-io
    state: latest
  when: "ansible_os_family == 'RedHat'"
  tags: [docker]

- name: Docker is present Amazon
  yum:
    name: docker
    state: latest
  when: "ansible_distribution == 'Amazon'"
  tags: [docker]

- name: Python-pip is present
  apt: name=python-pip state=present
  when: "ansible_os_family == 'Debian'"
  tags: [docker]

- name: Python-pip is present
  yum: name={{ item }} state=present
  with_items:
    libselinux-python
    python-pip
  when: "ansible_os_family == 'RedHat'"
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.2.3
    state: present
  tags: [docker]

- name: Files are present
  copy:
    src: docker
    dest: /etc/default/docker
  register: copy_result
  tags: [docker]

- name: Docker service is restarted centos
  shell: sudo docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d &
  when: "ansible_os_family == 'RedHat'"
#  service:
#    name: docker
#    state: restarted
#  when: copy_result|changed
  tags: [docker]
- name: Docker service is restarted ubuntu
# shell: sudo docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d &
  service:
    name: docker
    state: restarted
  when: "ansible_os_family == 'Debian'"
  tags: [docker]
