--- # Master playbook
- hosts: apacheweb
  user: henry
  become: yes
  connection: ssh
  gather_facts: yes
  pre_tasks:
  - name: Start time
    raw: date > /home/henry/log/time.log
  roles: 
    - redhat_webservers
  post_tasks:
  - name: Start time
    raw: date >> /home/henry/log/time.log

